### ISSUE TITLE
sell [amount] or quota always fail

### ISSUE THREAD

**Issue by PunishedSnakePr** [stormytuna/SellFromTerminal#1]
Hi. I suppose this issue comes up in combination with other mods I have installed (018d2dad-094a-3f98-957e-29845528b6b4) but "sell [amount]" and "sell quota" always fail reporting there's not enough loot in the ship. Let me know if you need more information.

**Comment by stormytuna** [comment]
Can you identify which mod(s) are causing the problem?

**Comment by PunishedSnakePr** [comment]
I can try to in the next days and get back to you with my findings.

**Comment by PunishedSnakePr** [comment]
Does Commit 051f9ed fix this?

**Comment by PunishedSnakePr** [comment]
Ok, I will check and let you know. Just wasn't sure if the fix was directly related to this issue.

**Comment by PunishedSnakePr** [comment]
So, the good news is: Selling stuff works now (sell amount and sell quota behave the same in my testing), BUT not as expected :D

Here is the scenario: Quota is 130, deadline is reached (0 days left) and I go to the company moon to sell stuff.
1) Attached PNG (stormytuna.SellFromTerminal) shows my general MOD config.
2) Second attached PNG (BeforeSellLootScan) shows a scan of all my loot in the ship before selling.
3) Next PNG (BeforeSellQuotaTerminal) shows the terminal after typing "sell quota" and before confirm.
4) PNG AfterSellQuotaTerminal shows the terminal after confirmation of selling quota.
5) Last PNG (AfterSellQuotaScan) shows my ship loot after selling quota.

So, I automatically sold the laser pointer and an axle which are worth 151. There are probably tons of ways to calculate the quota (just think of the laser pointer and pickles) but 151 is out of reach and even beyond my config.

I hope I was more precise this time! :) Let me know if you need something else.

**Comment by stormytuna** [comment]
Yep, that was enough - it was an issue with how the allowance amount worked

Closing as fixed in 3ffde0296dc6b5d5282e4a2c932da5eec6d0f7e9
