### ISSUE TITLE
Mod is breaking 'other' command and ExtraDaysToDeadline command.

### ISSUE THREAD

**Issue by Re-VelatoR** [stormytuna/SellFromTerminal#3]
This is the error it throws when attempting to input 'other' or 'buyday' (from ExtraDaysToDeadline) into the terminal. Only other mods that add terminal commands are BetterShotgunShells, LethalThings, DetailedScan, and LategameUpgrades. Those commands work fine.

![Untitled](https://github.com/stormytuna/SellFromTerminal/assets/53530168/1e8049a2-fd3b-4130-ac1d-4eb5d6837bdc)

**Comment by stormytuna** [comment]
Closing as fixed in [051f9ed](https://github.com/stormytuna/SellFromTerminal/commit/051f9ed16a8860299b51e3eb57476e6c7111ef84)
