### ISSUE TITLE
Error in Log on loading a Game

### ISSUE THREAD

**Issue by CommanderSlav** [stormytuna/SellFromTerminal#6]
I was digging through for a different error for something else, but I noticed that this error generates in the log upon loading into a save. Fresh or not. 
I'm frankly not sure if this is or could be causing any issues. 
![image](https://github.com/stormytuna/SellFromTerminal/assets/67171084/7fddf442-ba9e-44a8-a5b5-d1e4d88e3b18)

This is my mod code: 018d6501-4d95-b19b-cd9e-cd42298c6e88 

Dependency String:
BepInEx-BepInExPack-5.4.2100
Evaisa-HookGenPatcher-0.0.5
Evaisa-LethalLib-0.14.2
sunnobunno-YippeeMod-1.2.3
Evaisa-LethalThings-0.9.4
x753-Mimics-2.3.2
RugbugRedfern-Skinwalkers-4.0.1
PopleZoo-BetterItemScan-3.0.1
NotAtomicBomb-TerminalApi-1.5.1
rafl-BonkHitSfxFixed-1.0.2
EladNLG-EladsHUD-1.2.1
Renegades-WalkieUse-1.5.0
FlipMods-BetterStamina-1.3.2
AllToasters-SpectateEnemies-2.2.1
MegaPiggy-BuyableShotgunShells-1.0.5
MassiveNewCoilers-FixCentipedeLag-2023.12.7
kyxino-LethalUtilities-1.2.21
AlexCodesGames-AdditionalContentFramework-1.0.3
AinaVT-LethalConfig-1.3.4
KodiCraft-TermSpeak-1.1.0
kuba6000-LC_Masked_Fix-0.0.2
HomelessGinger-MaskedEnemyOverhaul-3.1.2
TheFluff-FairAI-1.3.2
LethalAPI-LethalAPI_Terminal-1.0.1
ZG-BetterTerminal-1.1.1
taffyko-BetterSprayPaint-2.0.2
bigmcnugget-VanillaContentExpansion-0.1.8
ShaosilGaming-GeneralImprovements-1.1.6
AgentRev-ShootableMouthDogs-1.0.1
DannyVD-MonitorLabels-1.3.1
TheDeadSnake-Touchscreen-1.0.10
CapyCat-Solos_Ring_Compass-1.0.3
extraes-LethalLoudnessMeter-1.0.2
ViViKo-BetterDecorPlacement-1.2.1
bozzobrain-ShipMaid-3.2.7
MrHydralisk-EnhancedLockpicker-1.1.3
xCeezy-LethalEscape-0.8.5
jockie-LethalExpansionCore-1.3.15
Justice69-ImmersiveScraps-1.1.8
Zaggy1024-PathfindingLagFix-1.2.1
DerplingDevelopments-SavageCompany-1.1.3
loaforc-FacilityMeltdown-2.1.1
ION-ToggleDeafen-1.1.1
Ozone-Runtime_Netcode_Patcher-0.2.5
readthisifbad-SnatchinBracken-1.3.6
NiceHairs-NuclearLib-1.0.4
NiceHairs-Symbiosis-1.0.5
FlipMods-FasterItemDropship-1.2.1
Zaggy1024-OpenBodyCams-1.1.1
saint_kendrick-Lethal_Doors-1.0.4
Zaggy1024-NutcrackerFixes-1.2.2
EliteMasterEric-CleanerLogs-1.0.0
linkoid-DissonanceLagFix-1.0.0
BlueAmulet-LogNeuter-1.0.3
falcodxb-LessLogs-1.0.1
EliteMasterEric-Coroner-1.5.3
malco-Lategame_Upgrades-3.1.1
Anubis-LaserControl-0.1.3
Financier-GhostGirlFearReset-1.0.0
Team_GLV-AdditionalSuits-2.0.0
Hexnet111-SuitSaver-1.1.4
x753-More_Suits-1.4.1
darmuh-suitsTerminal-1.0.6
PotatoePet-AdvancedCompany-1.0.148
stormytuna-SellFromTerminal-1.1.2
DOkge-InventoryFixPlugin-0.0.1
Sophisticasean-KeysLockDoors-1.1.2
Rune580-LethalCompany_InputUtils-0.6.1
GiGaGon-ScrapMerging-1.0.3
MrHydralisk-EnhancedRadarBooster-1.6.2
readthisifbad-KillableEnemies-0.1.1

**Comment by stormytuna** [comment]
Seems like a conflict with another mod as I can't repro. I don't really have time to look into every single mod conflict - if you can narrow it down to a specific mod I can look into it further

**Comment by CommanderSlav** [comment]
I'm guessing this may have been due to an older version of a mod. Retesting this with all my mods updated (2/8/2024) the issue no longer occurs. I'm gonna mark this one as closed and not an issue with your mod as the culprit. Thanks again.
