### ISSUE TITLE
Mod breaks Turret/Mine terminal commands

### ISSUE THREAD

**Issue by Audisek** [stormytuna/SellFromTerminal#8]
When I use for example terminal command "C1" which disables turrets or mines, there's an error in TryReturnSpecialNodes(), because __result is NULL.

This causes the terminal to not clear and I have to backspace to delete the input after the "C1" command.

I just work around this by adding this condition, but imo someone who's better at modding should officially fix it in a more elegant way. Thanks. (The same bug is also in the RouteRandom mod and the same workaround works for it as well.)

![image](https://github.com/stormytuna/SellFromTerminal/assets/32688435/64c1ce4a-50da-4ee1-98ef-c6012e20136f)

**Comment by stormytuna** [comment]
Closing as fixed in 1fd0820e78d734db8fa71c9563853aa4eb46b514
